### ISSUE TITLE
java.lang.RuntimeException: Attempted to register ID ResourceKey[minecraft:entity_type / minecraft:sheep] at different raw IDs (74, 499)! If you're trying to override an item, use .set(), not .register()!

### ISSUE THREAD

**Issue by TheButterbrotMan** [suppergerrie2/ChonkySheep#3]
https://pastebin.com/BHd9Jc1w

**Comment by suppergerrie2** [comment]
I cannot reproduce the crash but I may have a fixed version. Would you be open to testing it?

**Comment by TheButterbrotMan** [comment]
sure

**Comment by suppergerrie2** [comment]
[chonky_sheep-2.1.0.zip](https://github.com/suppergerrie2/ChonkySheep/files/7834912/chonky_sheep-2.1.0.zip)
It's uploaded as a zip due to github not allowing .jar files, so you'll need to extract it into your mod folder

**Comment by suppergerrie2** [comment]
I have uploaded a new version on curseforge which should fix this. Feel free to reopen if it happens again
